=== Integrative-Transcriptomics/Mayday-core/src/main/resources/mayday/interpreter/rinterpreter/RSourceDescription.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ELEMENT RSourceDescription (functionname, quickinfo, paramlist, requires?)>

  <!ELEMENT functionname EMPTY>
    <!ATTLIST functionname id (CDATA) #REQUIRED>
    <!ATTLIST functionname descriptor (CDATA) #IMPLIED>

  <!ELEMENT quickinfo (#PCDATA)>

  <!ELEMENT paramlist (param*)>
     <!ELEMENT param (type?)>
		<!ATTLIST param name (CDATA) #REQUIRED>
		<!ATTLIST param default (CDATA) #IMPLIED>
		<!ATTLIST param description (CDATA) #IMPLIED>
		
		<!ELEMENT type (entry*)>
		   <!ATTLIST type name (CDATA) #IMPLIED>
		   <!ATTLIST type noedit (CDATA) #IMPLIED>
		   <!ELEMENT entry EMPTY>
		      <!ATTLIST entry value (CDATA) #REQUIRED>
		      
  <!--  The following tag is used to indicate which MIOGroups should
     %  be selected to fulfill the R functions requirements
     %  properly.
     %  The mioclass attribute is required. Only MIOGroups
     %  containing such values are interesting.
     %  The description attribute is needed to inform the
     %  user about the purpose of the MIOGroup. Thus it is not a
     %  strict requirement to fulfill the exact description
     %  of the corresponding MIOGroup.
     %
     %  The order is important!
    -->	      
  <!ELEMENT requires (mio*)>
    <!ELEMENT mio EMPTY>
      <!ATTLIST mio id (CDATA) #REQUIRED>
      <!ATTLIST mio classname (CDATA) #REQUIRED>
      <!ATTLIST mio dir (CDATA) #IMPLIED>

=== Integrative-Transcriptomics/Mayday-core/src/main/resources/mayday/interpreter/rinterpreter/examples/SimpleKmeans.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE RSourceDescription SYSTEM 'RSourceDescription.dtd'>

<RSourceDescription>
	<functionname id="run" descriptor="Simple k-means"/>
	<quickinfo><![CDATA[#
#  Simple k-means algorithm (see pckg. {mva})
#
#  "R for Mayday" example showing how to return 
#  only probe lists 
#
]]></quickinfo>
	<paramlist>
		<param name="DATA" description="Mayday's data structures"/>
		<param name="k" default="10" description="number of clusters to produce"/>
		<param name="iter.max" default="10" description="max. number of iterations"/>
	</paramlist>
	<requires>
	</requires>
</RSourceDescription>

=== Integrative-Transcriptomics/Mayday-core/src/main/resources/mayday/affyrma/interpreter/RMA_normalization.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE RSourceDescription SYSTEM 'RSourceDescription.dtd'>

<RSourceDescription>
	<functionname id="run" descriptor="RMA-Normalization"/>
	<quickinfo><![CDATA[#  
#  RMA-Normalization 'R for Mayday'.
#  
# annotation.name='RMA-Normalized Data'
# ---
#  Anna Jasper, 2007-03-28
#  Anna.ivic@gmail.com
#
# -------------------------------------------------------------------
]]></quickinfo>
	<paramlist>
		<param name="DATA" description="Mayday's data structures"/>
		<param name="files" default=".cel" description="filelist">
		   <type name="filenames"/>
		</param>
		<param name=" CelfilePath"/>
		<param name=" SampleNames"/>
		<param name=" PhenoData"/>
		<param name=" Description"/>
		<param name=" Notes"/>
		<param name=" rmMask"/>
		<param name=" rmOutliers"/>
		<param name=" rmExtra"/>
		<param name=" Hdf5"/>
		<param name=" Hdf5FilePath"/>
		<param name=" Verbose"/>
		<param name=" Normalize"/>
		<param name=" Background"/>
		<param name=" BGversion"/>
		<param name=" Destructive"/>
		<param name=" CDFname"/>
	</paramlist>
</RSourceDescription>

=== Integrative-Transcriptomics/Mayday-core/src/main/resources/mayday/interpreter/rinterpreter/examples/cluster.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE RSourceDescription SYSTEM 'RSourceDescription.dtd'>

<RSourceDescription>
	<functionname id="run" descriptor="PAM"/>
	<quickinfo><![CDATA[#  
#  PAM (Partitioning Around Medoids)
#
#  Cluster microarray data using different
#  dissimilarity measures.
#
#  This application makes use of the 'pam'
#  function from the 'cluster' package.
#
]]></quickinfo>
	<paramlist>
		<param name="DATA" description="Mayday's data structures"/>
		<param name="k" default="2" description="number of clusters"/>
		<param name="metric" default="&quot;euclidean&quot;" description="metric to be used">
			<type name="selection">
				<entry value="&quot;euclidean&quot;"/>
				<entry value="&quot;manhattan&quot;"/>
			</type>
		</param>
		<param name="p" default="2" description="if metric is &quot;minkowsky&quot; the p-th root is used"/>
		<param name="plot" default="TRUE" description="plot the silhouettes?">
			<type name="strictboolean" noedit="false"/>
		</param>
	</paramlist>
	<requires>
	</requires>
</RSourceDescription>

=== Integrative-Transcriptomics/Mayday-core/src/main/resources/mayday/interpreter/rinterpreter/examples/binning.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE RSourceDescription SYSTEM 'RSourceDescription.dtd'>

<RSourceDescription>
	<functionname id="run" descriptor="Binning"/>
	<quickinfo><![CDATA[#
# bins the expression matrix
#
# transform.method (transform data BEFORE binning):
#          - none    
#          - log (log transformation)
#          - sqrt
#
# binning.method: 
#          - scale (simply scales the intensities to the
#              range min-max.)
#          - rank  (same as scale, but uses the rank of
#              the intensities instead of intensities
#              directly)
#
# rounding.method:
#          - ceiling (returns the smallest integer not 
#               less than the float value)
#          - floor   (returns the largest integer not 
#               greater than the float value)
#          - round   (rounds the value.  Note that for 
#               rounding off a 5, the IEEE standard is 
#               used, "_go to the even digit_")
#
# min:    - n  (the smallest allowed binned value)
#
# max:    - n  (the greatest allowed binned value)
#
#
]]></quickinfo>
	<paramlist>
		<param name="DATA" description="Mayday's data structures"/>
		<param name="transform.method" default="&quot;none&quot;"/>
		<param name="binning.method" default="&quot;scale&quot;"/>
		<param name="rounding.method" default="&quot;round&quot;"/>
		<param name="min" default="0"/>
		<param name="max" default="3"/>
	</paramlist>
	<requires>
	</requires>
</RSourceDescription>

=== Integrative-Transcriptomics/Mayday-core/src/main/resources/mayday/interpreter/rinterpreter/examples/kmeans.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE RSourceDescription SYSTEM 'RSourceDescription.dtd'>

<RSourceDescription>
	<functionname id="run" descriptor="k-Means {mva}"/>
	<quickinfo><![CDATA[# 
#  kmeans, from the package mva
#
#  Example for "R for Mayday"
#  
#  Apply the k-means algorithm to the expression matrix.
#  
#
]]></quickinfo>
	<paramlist>
		<param name="DATA" description="Mayday's data structures"/>
		<param name="k" default="10" description="number of clusters"/>
		<param name="iterations" default="100" description="max number of iterations"/>
	</paramlist>
	<requires>
	</requires>
</RSourceDescription>
