=== Integrative-Transcriptomics/Mayday-core/src/main/resources/mayday/interpreter/rinterpreter/RSourceDescription.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ELEMENT RSourceDescription (functionname, quickinfo, paramlist, requires?)>

  <!ELEMENT functionname EMPTY>
    <!ATTLIST functionname id (CDATA) #REQUIRED>
    <!ATTLIST functionname descriptor (CDATA) #IMPLIED>

  <!ELEMENT quickinfo (#PCDATA)>

  <!ELEMENT paramlist (param*)>
     <!ELEMENT param (type?)>
		<!ATTLIST param name (CDATA) #REQUIRED>
		<!ATTLIST param default (CDATA) #IMPLIED>
		<!ATTLIST param description (CDATA) #IMPLIED>
		
		<!ELEMENT type (entry*)>
		   <!ATTLIST type name (CDATA) #IMPLIED>
		   <!ATTLIST type noedit (CDATA) #IMPLIED>
		   <!ELEMENT entry EMPTY>
		      <!ATTLIST entry value (CDATA) #REQUIRED>
		      
  <!--  The following tag is used to indicate which MIOGroups should
     %  be selected to fulfill the R functions requirements
     %  properly.
     %  The mioclass attribute is required. Only MIOGroups
     %  containing such values are interesting.
     %  The description attribute is needed to inform the
     %  user about the purpose of the MIOGroup. Thus it is not a
     %  strict requirement to fulfill the exact description
     %  of the corresponding MIOGroup.
     %
     %  The order is important!
    -->	      
  <!ELEMENT requires (mio*)>
    <!ELEMENT mio EMPTY>
      <!ATTLIST mio id (CDATA) #REQUIRED>
      <!ATTLIST mio classname (CDATA) #REQUIRED>
      <!ATTLIST mio dir (CDATA) #IMPLIED>

=== Integrative-Transcriptomics/Mayday-core/src/main/resources/mayday/interpreter/rinterpreter/examples/tTest.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE RSourceDescription SYSTEM 'RSourceDescription.dtd'>

<RSourceDescription>
	<functionname id="run" descriptor="t-Test"/>
	<quickinfo><![CDATA[#  
#  t-test application for 'R for Mayday'.
#  
#  A simple two-sample, two-sided t-test returning the call and
#  the p-value as MIOs.
#
#  2 probelists are created for up-regulated and down-regulated
#  probes.
#
#  The p-value, the call {-1,1} and if requested the mean of the
#  groups.
#
#  The t-test will always be performed over the whole mastertable.
#
#  NA values are ignored.
#
]]></quickinfo>
	<paramlist>
		<param name="DATA" description="Mayday's data structures"/>
		<param name=" 
	group.name.test"/>
		<param name=" cols.test"/>
		<param name=" 
	group.name.reference"/>
		<param name=" cols.reference"/>
		<param name="group.means" default="&quot;both&quot;" description="Which means should be returned">
			<type name="selection">
				<entry value="&quot;both&quot;"/>
				<entry value="&quot;test&quot;"/>
				<entry value="&quot;reference&quot;"/>
				<entry value="&quot;none&quot;"/>
			</type>
		</param>
		<param name="sig.level" default="0.05" description="Significance level"/>
	</paramlist>
	<requires>
		<mio id="signif" classname="mayday.core.mi.DoubleMIO" direction="OUT"/>
		<mio id="" classname="mayday.core.mi.DoubleMIO" direction="OUT"/>
	</requires>
</RSourceDescription>

=== Integrative-Transcriptomics/Mayday-core/src/main/resources/mayday/interpreter/rinterpreter/maintenance/create2Circles.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE RSourceDescription SYSTEM 'RSourceDescription.dtd'>

<RSourceDescription>
	<functionname id="run" descriptor="Support, Create 2 Circles"/>
	<quickinfo><![CDATA[#
#  R for Mayday, maintenance
#
#  Create a dataset with two circles
#
#  showing how to create a new DataSet
#
]]></quickinfo>
	<paramlist>
		<param name="DATA" description="Mayday's data structures"/>
		<param name="n" default="400" description="number of points per circle"/>
		<param name="radius.innercircle" default="1" description="mean of inner circles radius"/>
		<param name="radius.outercircle" default="2" description="mean of outer circles radius"/>
		<param name="sd" default="0.1" description="standard deviation for the random computation of the radii"/>
	</paramlist>
	<requires>
	</requires>
</RSourceDescription>

=== Integrative-Transcriptomics/Mayday-core/src/main/resources/mayday/interpreter/rinterpreter/examples/imputation.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE RSourceDescription SYSTEM 'RSourceDescription.dtd'>

<RSourceDescription>
	<functionname id="run" descriptor="Impute"/>
	<quickinfo><![CDATA[#  
#  Imputation. (k-nearest neighbor)
#  
#  Guess missing values with the function
#  impute.knn() from the package {impute}
#
#  Requires package {impute}!
#
]]></quickinfo>
	<paramlist>
		<param name="DATA" description="Mayday's data structures"/>
		<param name="k" default="10"/>
		<param name="rowmax" default="0.5"/>
		<param name="colmax" default="0.8"/>
		<param name="maxp" default="1500"/>
	</paramlist>
	<requires>
	</requires>
</RSourceDescription>

=== Integrative-Transcriptomics/Mayday-core/src/main/resources/mayday/interpreter/rinterpreter/maintenance/smallData.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE RSourceDescription SYSTEM 'RSourceDescription.dtd'>

<RSourceDescription>
	<functionname id="run" descriptor="Support, Create a Small Data Set"/>
	<quickinfo><![CDATA[#
# R for Mayday, maintenance
#
#   create a small dataset with 
#     n probes 
#     m experiments 
#   
#   the output contains two mios:
#     mean
#     variance
#
]]></quickinfo>
	<paramlist>
		<param name="DATA" description="Mayday's data structures"/>
		<param name="n" default="20" description="number of probes">
			<type name="default" noedit="false"/>
		</param>
		<param name="m" default="5" description="number of experiments">
			<type name="default" noedit="false"/>
		</param>
	</paramlist>
	<requires>
		<mio id="" classname="mayday.core.mi.DoubleMIO" direction="OUT"/>
		<mio id="" classname="mayday.core.mi.DoubleMIO" direction="OUT"/>
	</requires>
</RSourceDescription>

=== Integrative-Transcriptomics/Mayday-core/src/main/resources/mayday/interpreter/rinterpreter/examples/spectralClustering.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE RSourceDescription SYSTEM 'RSourceDescription.dtd'>

<RSourceDescription>
	<functionname id="run" descriptor="Spectral Clustering"/>
	<quickinfo><![CDATA[#
#  Spectral Clustering
#
#  Example for "R for Mayday"
#
#  Spectral clustering:
#  Ref: A. Y. Ng, M. I. Jordan, Yair Weiss. 
#       On Spectral Clustering: Analysis and an algorithm. 
#       In NIPS 14. 2002
#
]]></quickinfo>
	<paramlist>
		<param name="DATA" description="Mayday's data structures"/>
		<param name="k" default="2" description="number of clusters"/>
		<param name="sigma" default="0.1" description="scaling factor"/>
		<param name="kmeans.iter.max" default="10" description="number of max. kmeans-iterations"/>
		<param name="plot.Y" default="TRUE" description="indicating whether to plot the Y-matrix">
			<type name="strictboolean" noedit="false"/>
		</param>
	</paramlist>
	<requires>
	</requires>
</RSourceDescription>

=== Integrative-Transcriptomics/Mayday-core/src/main/resources/mayday/affyrma/interpreter/GCRMA_normalization.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE RSourceDescription SYSTEM 'RSourceDescription.dtd'>

<RSourceDescription>
	<functionname id="run" descriptor="GCRMA-Normalization"/>
	<quickinfo><![CDATA[#  
#  GCRMA-Normalization 'R for Mayday'.
#  
# annotation.name='GCRMA-Normalized Data'
# ---
#  Anna Jasper, 2007-03-28
#  Anna.ivic@gmail.com
#
# -------------------------------------------------------------------
]]></quickinfo>
	<paramlist>
		<param name="DATA" description="Mayday's data structures"/>
		<param name="files" default=".cel" description="filelist">
		   <type name="filenames"/>
		</param>
		<param name=" Compress"/>
		<param name=" CelfilePath"/>
		<param name=" SampleNames"/>
		<param name=" PhenoData"/>
		<param name=" Description"/>
		<param name=" Notes"/>
		<param name=" Normalize"/>
		<param name=" Bgversion"/>
		<param name=" Type"/>
		<param name=" K"/>
		<param name=" Stretch"/>
		<param name=" Correction"/>
		<param name=" Rho"/>
		<param name=" OpticalCorrect"/>
		<param name=" Verbose"/>
		<param name=" Fast"/>
		<param name=" Minimum"/>
		<param name=" OptimizeBy"/>
		<param name=" Cdfname"/>
	</paramlist>
</RSourceDescription>

=== Integrative-Transcriptomics/Mayday-core/src/main/resources/mayday/interpreter/rinterpreter/examples/scatterPlot.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE RSourceDescription SYSTEM 'RSourceDescription.dtd'>

<RSourceDescription>
	<functionname id="run" descriptor="Scatter-Plots (2D/3D)"/>
	<quickinfo><![CDATA[#
#  Scatterplot of the probes contained in the given 
#  probelists
#
#  Plots 2 or 3 experiments of all explicit probes, the
#  experiments can be given either as integers or
#  as experiment identifiers
#
]]></quickinfo>
	<paramlist>
		<param name="DATA" description="Mayday's data structures"/>
		<param name="exp1" default="1" description="first experiment (to appear on X-axis)"/>
		<param name="exp2" default="2" description="second experiment (to appear on Y-axis)"/>
		<param name="exp3" default="NULL" description="third experiment (to appear on Z-axis; pckg. scatterPlot3d must be installed)"/>
	</paramlist>
	<requires>
	</requires>
</RSourceDescription>

=== Integrative-Transcriptomics/Mayday-core/src/main/resources/mayday/interpreter/rinterpreter/examples/MDS.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE RSourceDescription SYSTEM 'RSourceDescription.dtd'>

<RSourceDescription>
	<functionname id="run" descriptor="Multidimensional Scaling"/>
	<quickinfo><![CDATA[#
# multidimensional scaling, using 
#    cmdscale {mva} (classical metric multidim. scaling), 
#    isoMDS {MASS} (Kruskal's non-metric MDS) or
#    sammon {MASS} (Sammon's non-linear mapping)
#
#  R for Mayday example showing the creation of a new
#  MasterTable and DataSet
#
#  Afterwards, a clustering is made.
# 
]]></quickinfo>
	<paramlist>
		<param name="DATA" description="Mayday's data structures"/>
		<param name="method" default="&quot;cmdscale&quot;" description="method; one out of {&quot;cmdscale&quot;, &quot;isoMDS&quot;,&quot;sammon&quot;}">
			<type name="selection">
				<entry value="&quot;cmdscale&quot;"/>
				<entry value="&quot;isoMDS&quot;"/>
				<entry value="&quot;sammon&quot;"/>
			</type>
		</param>
		<param name="k" default="3" description="number of dimensions to return">
			<type name="default" noedit="false"/>
		</param>
		<param name="n.clust" default="3" description="number of clusters">
			<type name="default" noedit="false"/>
		</param>
	</paramlist>
	<requires>
	</requires>
</RSourceDescription>
